### ISSUE TITLE
Text#width and Text#height are not present in Text after creation

### ISSUE THREAD

**Issue by lstrzebinczyk** [simple2d/simple2d.js#1]
After calling `S2D.SetText` with text, the text variable leaves with height and width properties, as set up here: https://github.com/simple2d/simple2d.js/blob/master/src/text.js#L49-L50

However, after creation of text, that is, after calling `S2D.CreateText`, present here: https://github.com/simple2d/simple2d.js/blob/master/src/text.js#L6 , those variables are not present.

Unified behavior and existance of `width` and `height` are required to be able to use them in ruby wrapper.

I was trying to use `S2D.SetText` inside `S2D.CreateText`, but it throws exceptions about textures and S2D.GL being null.

Do you have any ideas on how this could be fixed?

**Comment by blacktm** [comment]
Fixed in b5fd2a9a3f7cfbc261fc04b19c77b1d4930e47c2. This ends up calling `S2D.SetText` inside `S2D.CreateText`, like you mention, by adding guards so as not to call GL functions before the context is present.

**Comment by lstrzebinczyk** [comment]
Nice!
